image: maven:3.9.9-eclipse-temurin-17

stages:
  - build
  - test
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-B -e -V"

cache:
  paths:
    - .m2/repository

before_script:
  - echo "Java version"
  - java -version
  - echo "Maven version"
  - mvn -version

# ---------------- BUILD ----------------
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

# ---------------- TEST + COVERAGE ----------------
test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/*.xml
      coverage_report:
        coverage_format: cobertura
        path: target/site/jacoco/jacoco.xml
    paths:
      - target/site/jacoco
    expire_in: 1 week

# ---------------- PACKAGE ----------------
package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week