image: maven:3.9.9-eclipse-temurin-11

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn -B -DskipTests clean package -s settings.xml

test:
  stage: test
  script:
    - mvn -B test -s settings.xml

deploy:
  stage: deploy
  script:
    - mvn deploy -s settings.xml -DskipTests
  only:
    - main