image: maven:3.9.9-eclipse-temurin-11

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository

before_script:
  - echo "Using Maven"
  - mvn -version

build:
  stage: build
  script:
    - mvn -B -DskipTests clean package

test:
  stage: test
  script:
    - mvn -B test

deploy:
  stage: deploy
  script:
    - mvn deploy -s settings.xml