@startuml tile_package
title COO Project - tile package

package tile {
    class Tile {
        - Edge topEdge
        - Edge rightEdge
        - Edge bottomEdge
        - Edge leftEdge
        - HashMap<Direction, Direction> roadConnections
        - HashSet<Direction> finishingRoads
        - Orientation orientation
        
        + Tile(Edge topEdge, Edge rightEdge, Edge bottomEdge, Edge leftEdge)
        + Tile(Edge topEdge, Edge rightEdge, Edge bottomEdge, Edge leftEdge, Orientation orientation)
        + Orientation getOrientation()
        + Edge getEdge(Direction direction)
        + boolean isRoadTerminated(Direction direction)
        + Direction getExitRoadDirection(Direction enterDirection) throws NoRoadException
        + void connectRoad(Direction direction1, Direction direction2) throws NoRoadException
        + void terminateRoad(Direction direction) throws NoRoadException
        + boolean isCompatibleWith(Tile other, Direction direction)
    }
    
    class TileBuilder {
        + TileBuilder()
        + Tile build(String string) throws WrongTileSyntaxException
    }
    
    enum Direction {
        TOP
        RIGHT
        BOTTOM
        LEFT
        
        + Direction getOldDirection(Orientation orientation)
        + Direction getNewDirection(Orientation orientation)
        + Direction toOpposite()
        + Direction toLeft()
        + Direction toRight()
    }
    
    enum Orientation {
        NORTH
        EAST
        SOUTH
        WEST
    }
    
    together {
        exception NoRoadException {
            + NoRoadException(String message)
        }
        
        exception WrongTileSyntaxException {
            + WrongTileSyntaxException(String message)
        }
    }
    
    Tile "1" *-- "4" Edge : contains
    Tile --> Direction : uses
    Tile --> Orientation : has
    TileBuilder ..> Tile : creates
    TileBuilder ..> Direction : uses
    TileBuilder ..> Orientation : uses
    TileBuilder ..> Edge : creates
    Tile ..> NoRoadException : throws
    TileBuilder ..> WrongTileSyntaxException : throws
}

@enduml
